capture = x11
min_log_level = 4
system_tray = disabled
touchpad_as_ds4 = disabled
motion_as_ds4 = disabled
native_pen_touch = disabled
ds5_inputtino_randomize_mac = disabled
global_prep_cmd = [{"do":"echo \"restore saves\"","undo":"echo \"upload saves\""}]
port = 47989

